### ISSUE TITLE
Where are these unit types  defined?

### ISSUE THREAD

**Issue by martinmestre** [JuliaAstroSim/AstroIC#3]
Hello, I would like to know where are the following types (I, Len, MASS, GM) defined:
``` 
mutable struct PlummerStarCluster{I, Len, MASS, GM} <: InitialConditionConfig
    collection::Collection
    NumSamples::I

    VirialRadius::Len

    TotalMass::MASS

    model::GM
end
```
I ask because I would like to define them in my own code. I have searched for in this package and related ones, but couldn't find it.
Thank you very much.
Best.

**Comment by islent** [comment]
Hi~
These are parametric types, see the doc here: https://docs.julialang.org/en/v1/manual/types/#man-parametric-composite-types

In general, `{I, Len, MASS, GM}` could be named to anything, for example, `{E, F, G, H}`. However, they must be inherited from parent structs:
```julia
struct YourStruct{A, B, C, D, I, Len, Mass, GM}
    a::A
    b::B
    ...
    cluster::PlummerStarCluster{I, Len, Mass, GM}
    ...
end
```

**Comment by martinmestre** [comment]
Ok, thanks for the answer.
